import { describe, it } from "node:test";
import assert from "node:assert";
import { CloudflareR2Signer } from "./cloudflare-r2-signer.server.ts";
import { AppError } from "../../lib/errors.ts";

describe("CloudflareR2Signer", () => {
  const TEST_CONFIG = {
    accountId: "00000000000000000000000000000000",
    bucket: "test-bucket",
    accessKeyId: "test-access-key",
    secretAccessKey: "test-secret-key",
    clock: () => 1234567890000,
  };

  const VALID_OBJECT_KEY = "videofetch/jobs/00000000000000000000000000000000/11111111111111111111111111111111";

  function getValidUrl(ttl: number) {
    const d = new Date(1234567890000);
    const amzDate = d.toISOString().replace(/[:-]/g, "").split(".")[0] + "Z";
    const sig = "a".repeat(64);
    return `https://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/${VALID_OBJECT_KEY}?X-Amz-Expires=${ttl}&X-Amz-Date=${amzDate}&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Signature=${sig}`;
  }

  it("fails if objectKey is invalid", async () => {
    const signer = new CloudflareR2Signer(TEST_CONFIG, async () => "https://example.com");
    await assert.rejects(
      async () => signer.signGet({ objectKey: "../invalid" as any, expiresAt: 1234567890000 + 10000 }),
      (err: any) => err.name === "ZodError"
    );
  });

  it("throws EXPIRED if job is already expired", async () => {
    const signer = new CloudflareR2Signer(TEST_CONFIG, async () => "https://example.com");
    await assert.rejects(
      async () => signer.signGet({ objectKey: VALID_OBJECT_KEY as any, expiresAt: 1234567890000 - 1000 }),
      (err: any) => err instanceof AppError && err.code === "EXPIRED"
    );
  });

  it("throws EXPIRED if remaining time is 999ms", async () => {
    const signer = new CloudflareR2Signer(TEST_CONFIG, async () => "https://example.com");
    await assert.rejects(
      async () => signer.signGet({ objectKey: VALID_OBJECT_KEY as any, expiresAt: 1234567890000 + 999 }),
      (err: any) => err instanceof AppError && err.code === "EXPIRED"
    );
  });

  it("floors TTL and caps at 300s", async () => {
    let capturedTtl = 0;
    const mockPresigner: any = async (client: any, cmd: any, opts: any) => {
      capturedTtl = opts.expiresIn;
      return getValidUrl(opts.expiresIn);
    };

    const signer = new CloudflareR2Signer(TEST_CONFIG, mockPresigner);

    const now = 1234567890000;
    let res = await signer.signGet({ objectKey: VALID_OBJECT_KEY as any, expiresAt: now + 1000 });
    assert.strictEqual(capturedTtl, 1);
    assert.ok(res.expiresAt <= now + 1000);

    res = await signer.signGet({ objectKey: VALID_OBJECT_KEY as any, expiresAt: now + 305000 });
    assert.strictEqual(capturedTtl, 300);
    assert.ok(res.expiresAt <= now + 305000);
  });

  it("rejects malicious URLs generated by presigner", async () => {
    const d = new Date(1234567890000);
    const amzDate = d.toISOString().replace(/[:-]/g, "").split(".")[0] + "Z";
    const sig = "a".repeat(64);

    const maliciousPresigners = [
      `http://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/${VALID_OBJECT_KEY}?X-Amz-Expires=10&X-Amz-Date=${amzDate}&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Signature=${sig}`, // http
      `https://attacker.com/test-bucket/${VALID_OBJECT_KEY}?X-Amz-Expires=10&X-Amz-Date=${amzDate}&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Signature=${sig}`, // wrong host
      `https://00000000000000000000000000000000.r2.cloudflarestorage.com/wrong-bucket/${VALID_OBJECT_KEY}?X-Amz-Expires=10&X-Amz-Date=${amzDate}&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Signature=${sig}`, // wrong bucket
      `https://user:pass@00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/${VALID_OBJECT_KEY}?X-Amz-Expires=10&X-Amz-Date=${amzDate}&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Signature=${sig}`, // credentials
      `https://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/${VALID_OBJECT_KEY}?X-Amz-Expires=10&X-Amz-Date=${amzDate}&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Signature=${sig}#frag`, // fragment
      `https://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/wrong-key?X-Amz-Expires=10&X-Amz-Date=${amzDate}&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Signature=${sig}`, // wrong key
      `https://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/${VALID_OBJECT_KEY}?X-Amz-Expires=10&X-Amz-Date=${amzDate}&X-Amz-Algorithm=AWS4-HMAC-SHA256`, // no sig
      `https://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/${VALID_OBJECT_KEY}?X-Amz-Expires=604800&X-Amz-Date=${amzDate}&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Signature=${sig}`, // wrong ttl
    ];

    for (const url of maliciousPresigners) {
      const signer = new CloudflareR2Signer(TEST_CONFIG, async () => url);
      await assert.rejects(
        async () => signer.signGet({ objectKey: VALID_OBJECT_KEY as any, expiresAt: 1234567890000 + 10000 }),
        (err: any) => err instanceof AppError && err.code === "PROCESSING_FAILED"
      );
    }
  });

  it("protects against raw presigner exception leaking details", async () => {
    const signer = new CloudflareR2Signer(TEST_CONFIG, async () => { throw new Error("AWS_SECRET_xyz"); });
    await assert.rejects(
      async () => signer.signGet({ objectKey: VALID_OBJECT_KEY as any, expiresAt: 1234567890000 + 10000 }),
      (err: any) => err instanceof AppError && err.code === "PROCESSING_FAILED" && !err.message.includes("AWS_SECRET")
    );
  });

  it("works with real AWS v3 getSignedUrl (no network)", async () => {
    const signer = new CloudflareR2Signer(TEST_CONFIG);

    const now = 1234567890000;
    const res = await signer.signGet({ objectKey: VALID_OBJECT_KEY as any, expiresAt: now + 60000 });
    assert.ok(res.url.startsWith("https://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/videofetch/jobs/00000000000000000000000000000000/11111111111111111111111111111111?"));
    assert.ok(res.url.includes("X-Amz-Signature="));
    assert.ok(res.url.includes("X-Amz-Expires=60"));
  });
});
