import { describe, it } from "node:test";
import assert from "node:assert";
import { CloudflareR2Signer } from "./cloudflare-r2-signer.server.ts";
import { AppError } from "../../lib/errors.ts";

describe("CloudflareR2Signer", () => {
  const TEST_CONFIG = {
    accountId: "00000000000000000000000000000000",
    bucket: "test-bucket",
    accessKeyId: "test-access-key",
    secretAccessKey: "test-secret-key",
  };

  const VALID_OBJECT_KEY = "videofetch/jobs/00000000000000000000000000000000/11111111111111111111111111111111";

  it("fails if objectKey is invalid", async () => {
    const signer = new CloudflareR2Signer(TEST_CONFIG, async () => "https://example.com");
    await assert.rejects(
      async () => signer.signGet({ objectKey: "../invalid", expiresAt: Date.now() + 10000 }),
      (err: any) => err.name === "ZodError"
    );
  });

  it("throws EXPIRED if job is already expired", async () => {
    const signer = new CloudflareR2Signer(TEST_CONFIG, async () => "https://example.com");
    await assert.rejects(
      async () => signer.signGet({ objectKey: VALID_OBJECT_KEY, expiresAt: Date.now() - 1000 }),
      (err: any) => err instanceof AppError && err.code === "EXPIRED"
    );
  });

  it("throws EXPIRED if remaining time is 999ms", async () => {
    const signer = new CloudflareR2Signer(TEST_CONFIG, async () => "https://example.com");
    await assert.rejects(
      async () => signer.signGet({ objectKey: VALID_OBJECT_KEY, expiresAt: Date.now() + 999 }),
      (err: any) => err instanceof AppError && err.code === "EXPIRED"
    );
  });

  it("floors TTL and caps at 300s", async () => {
    let capturedTtl = 0;
    const mockPresigner: any = async (client: any, cmd: any, opts: any) => {
      capturedTtl = opts.expiresIn;
      return `https://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/${VALID_OBJECT_KEY}?X-Amz-Signature=123`;
    };
    
    const signer = new CloudflareR2Signer(TEST_CONFIG, mockPresigner);

    // Test exact 1000ms -> 1s TTL
    let now = Date.now();
    let res = await signer.signGet({ objectKey: VALID_OBJECT_KEY, expiresAt: now + 1000 });
    assert.strictEqual(capturedTtl, 1);
    assert.ok(res.expiresAt <= now + 1000);

    // Test 305s -> 300s TTL
    now = Date.now();
    res = await signer.signGet({ objectKey: VALID_OBJECT_KEY, expiresAt: now + 305000 });
    assert.strictEqual(capturedTtl, 300);
    assert.ok(res.expiresAt <= now + 305000);
  });

  it("rejects malicious URLs generated by presigner", async () => {
    const maliciousPresigners = [
      "http://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/key?X-Amz-Signature=123", // http
      "https://attacker.com/test-bucket/key?X-Amz-Signature=123", // wrong host
      "https://00000000000000000000000000000000.r2.cloudflarestorage.com/wrong-bucket/key?X-Amz-Signature=123", // wrong bucket
      "https://user:pass@00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/key?X-Amz-Signature=123", // credentials
      "https://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/key?X-Amz-Signature=123#frag", // fragment
      "https://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/wrong-key?X-Amz-Signature=123", // wrong key
      "https://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/key?X-Amz-NoSig=123", // no sig
    ];

    for (const url of maliciousPresigners) {
      const signer = new CloudflareR2Signer(TEST_CONFIG, async () => url);
      await assert.rejects(
        async () => signer.signGet({ objectKey: VALID_OBJECT_KEY, expiresAt: Date.now() + 10000 }),
        (err: any) => err instanceof AppError && err.code === "PROCESSING_FAILED"
      );
    }
  });

  it("protects against raw presigner exception leaking details", async () => {
    const signer = new CloudflareR2Signer(TEST_CONFIG, async () => { throw new Error("AWS_SECRET_xyz"); });
    await assert.rejects(
      async () => signer.signGet({ objectKey: VALID_OBJECT_KEY, expiresAt: Date.now() + 10000 }),
      (err: any) => err instanceof AppError && err.code === "PROCESSING_FAILED" && !err.message.includes("AWS_SECRET")
    );
  });

  it("works with real AWS v3 getSignedUrl (no network)", async () => {
    // We pass undefined for presigner to use the real one.
    const signer = new CloudflareR2Signer(TEST_CONFIG);
    
    // We use actual SDK getSignedUrl.
    const now = Date.now();
    const res = await signer.signGet({ objectKey: VALID_OBJECT_KEY, expiresAt: now + 60000 });
    assert.ok(res.url.startsWith("https://00000000000000000000000000000000.r2.cloudflarestorage.com/test-bucket/videofetch/jobs/00000000000000000000000000000000/11111111111111111111111111111111?"));
    assert.ok(res.url.includes("X-Amz-Signature="));
    assert.ok(res.url.includes("X-Amz-Expires=60"));
  });
});
