import { describe, it, afterEach } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  SOURCE_QUALITY_MAX_COUNT,
  SOURCE_QUALITY_MAX_HEIGHT,
  SOURCE_QUALITY_WITHHELD_REASONS,
  SourceQualitySchema,
  VideoMetadataSchema,
  WorkerAnalyzeSuccessSchema,
  type SourceQuality,
} from "../../shared/worker/contracts.ts";
import { deriveExecutionPlan } from "../execution/format-plan.ts";
import { buildGenericFormatSelector } from "../execution/generic-source.ts";
import {
  YTDLP_ANALYSIS_MAX_RAW_FORMATS,
  analyzeGenericFormats,
  analyzeGenericMediaInternal,
  summarizeSourceQuality,
} from "./ytdlp-analysis.server.ts";
import {
  setSafeHttpTestHooks,
  type SafeRequestOnce,
} from "../../lib/security/safe-http.server.ts";
import { setProcessRunnerTestHooks } from "../../services/processing/process-runner.server.ts";
import { analyzeDirectMedia } from "../execution/direct-media.server.ts";

/**
 * GENERIC-SOURCE-RENDITION-INVENTORY-001 (Phase P1).
 *
 * Two claims are under test, and they pull in opposite directions:
 *
 *   1. the analysis now REPORTS what it observed and why each observed video
 *      rendition is not delivered;
 *   2. it changed NOTHING about what is delivered.
 *
 * Claim 2 is proven against a golden record generated by running the PRE-P1
 * analyzer (`main` d3a967b7) over the same corpus: metadata (minus the new
 * field), private selections, derived execution plans and the yt-dlp selectors
 * those plans produce. A change to any of them fails here, whatever the
 * inventory says.
 *
 * HLS-7 is a deliberate delivery change, and it is carved out rather than
 * regenerated: `HLS_ACTIVATED` names the ONE scenario whose clear-HLS rows are
 * now delivered, and for it the golden record still pins everything the
 * progressive family owns (see `testdata/README.md`).
 */

const TESTDATA = join(import.meta.dirname, "testdata");
const SAFE_URL = "https://example.invalid/watch/abc";

type Scenario = {
  readonly name: string;
  readonly ffmpegAvailable: boolean;
  readonly maxFileSizeBytes: number;
  readonly document?: Record<string, unknown>;
  readonly fixture?: string;
};

type GoldenEntry = {
  readonly ok: boolean;
  readonly code?: string;
  readonly video?: Record<string, unknown>;
  readonly selections?: Record<string, unknown>;
  readonly plans?: Record<string, unknown>;
  readonly selectors?: Record<string, string[]>;
};

const CORPUS = JSON.parse(
  readFileSync(join(TESTDATA, "source-quality-corpus.json"), "utf8"),
) as Scenario[];

const GOLDEN = JSON.parse(
  readFileSync(join(TESTDATA, "source-quality-preset-identity.golden.json"), "utf8"),
) as Record<string, GoldenEntry>;

function documentOf(scenario: Scenario): Record<string, unknown> {
  if (scenario.document) return scenario.document;
  assert.ok(scenario.fixture, `${scenario.name}: a scenario needs a document or a fixture`);
  return JSON.parse(readFileSync(join(TESTDATA, scenario.fixture), "utf8")) as Record<string, unknown>;
}

/** Runs the real internal analyzer over one scenario with a canned yt-dlp result. */
async function analyzeScenario(scenario: Scenario) {
  return analyzeGenericMediaInternal(SAFE_URL, {
    limits: {
      analysisTimeoutSeconds: 45,
      maxVideoDurationSeconds: 7200,
      maxFileSizeBytes: scenario.maxFileSizeBytes,
    },
    ffmpegAvailable: scenario.ffmpegAvailable,
    runner: async () => ({ code: 0, stdout: JSON.stringify(documentOf(scenario)), stderr: "" }),
    probeRuntime: async () => ({ available: true, version: "2026.08.19", reason: "ok" as const }),
    validateUrl: async (raw: string) => ({ url: raw, hostname: new URL(raw).hostname }),
  });
}

function sourceQualityOf(video: { sourceQuality?: SourceQuality }): SourceQuality {
  assert.ok(video.sourceQuality, "generic analysis must report sourceQuality");
  return video.sourceQuality;
}

/** A compact, exhaustive spelling of one expected summary. */
type Expected = {
  readonly observed: number | null;
  readonly deliverable: number | null;
  readonly withheld: ReadonlyArray<[string, number, number | null]>;
  readonly protectedUnenumerated?: boolean;
  readonly maybeProtectedObserved?: boolean;
};

/**
 * Every scenario's expected summary, written out rather than derived, so that a
 * change in classification has to be restated here to pass.
 */
const EXPECTED: Record<string, Expected> = {
  "case01-deliverable-progressive-ladder": { observed: 2160, deliverable: 2160, withheld: [] },
  // HLS-7: both admitted clear-HLS rows now back HLS-owned presets, so nothing
  // is withheld. Before HLS-7 this read deliverable 720 with the two HLS rows
  // withheld as `unsupported_protocol` (still the outcome without FFmpeg — see
  // the HLS-7 describe below). The audio-only HLS row is not a video rendition
  // and was never observed.
  "case02-clear-hls-above-progressive": {
    observed: 2160,
    deliverable: 2160,
    withheld: [],
  },
  "case03-segmented-dash-above-progressive": {
    observed: 2160,
    deliverable: 720,
    withheld: [["unsupported_protocol", 2, 2160]],
  },
  "case04-unsupported-container": {
    observed: 2160,
    deliverable: 720,
    withheld: [["unsupported_container", 2, 2160]],
  },
  "case05-split-pair-unsupported": {
    observed: 2160,
    deliverable: 720,
    withheld: [["split_pair_unsupported", 1, 2160]],
  },
  "case05b-audio-pair-unavailable": {
    observed: 2160,
    deliverable: 720,
    withheld: [["audio_pair_unavailable", 1, 2160]],
  },
  "case05c-no-worker-merge": {
    observed: 2160,
    deliverable: 720,
    withheld: [["split_pair_unsupported", 1, 2160]],
  },
  "case06-size-declared-over-limit": {
    observed: 2160,
    deliverable: 720,
    withheld: [["size_limit_exceeded", 1, 2160]],
  },
  "case06b-size-estimated-over-limit": {
    observed: 2160,
    deliverable: 720,
    withheld: [["size_limit_exceeded", 1, 2160]],
  },
  "case06c-pair-size-over-limit": {
    observed: 2160,
    deliverable: 720,
    withheld: [["size_limit_exceeded", 1, 2160]],
  },
  "case08-protected-unenumerated": {
    observed: 720,
    deliverable: 720,
    withheld: [],
    protectedUnenumerated: true,
  },
  "case09-maybe-protected-surviving": {
    observed: 720,
    deliverable: 720,
    withheld: [],
    maybeProtectedObserved: true,
  },
  "case10-unknown-audio-suppressed": {
    observed: 2160,
    deliverable: 720,
    withheld: [["fallback_suppressed", 1, 2160]],
  },
  "case10b-unknown-audio-suppressed-key-absent": {
    observed: 2160,
    deliverable: 720,
    withheld: [["fallback_suppressed", 1, 2160]],
  },
  "case11-not-selected-within-rung": {
    observed: 4320,
    deliverable: 2160,
    withheld: [["not_selected", 2, 4320]],
  },
  "case12-unsafe-selector-identity": {
    observed: 1080,
    deliverable: 720,
    withheld: [["unsafe_selector_identity", 1, 1080]],
  },
  "case13-contradictory-stream-shape": {
    observed: 1080,
    deliverable: 720,
    withheld: [["unsupported_stream_shape", 1, 1080]],
  },
  "case14-junk-rows-never-observed": { observed: 720, deliverable: 720, withheld: [] },
  "case15-split-ladder": {
    observed: 2160,
    deliverable: 2160,
    withheld: [["not_selected", 2, 2160]],
  },
  "case16-unknown-height-not-selected": {
    observed: 720,
    deliverable: 720,
    withheld: [["not_selected", 1, null]],
  },
  "case17-unknown-tier-when-merge-unavailable": {
    observed: 1080,
    deliverable: 480,
    withheld: [["split_pair_unsupported", 1, 1080]],
  },
  "case18-hostile-height-not-a-fact": {
    observed: 720,
    deliverable: 720,
    withheld: [["unsupported_protocol", 1, null]],
  },
  "case19-protocol-missing": {
    observed: 1080,
    deliverable: 720,
    withheld: [["unsupported_protocol", 1, 1080]],
  },
  "case20-audio-only-result": { observed: null, deliverable: null, withheld: [] },
  "case07-pinned-generic-html5-no-audio-codec-ffmpeg": {
    observed: null,
    deliverable: null,
    withheld: [],
  },
  "case07-pinned-generic-html5-no-audio-codec-no-ffmpeg": {
    observed: null,
    deliverable: null,
    withheld: [],
  },
  "x-synthetic-x-progressive-unknown-audio-ffmpeg": {
    observed: 720,
    deliverable: 360,
    withheld: [["unsupported_protocol", 2, 720]],
  },
  "x-synthetic-x-progressive-unknown-audio-no-ffmpeg": {
    observed: 720,
    deliverable: 360,
    withheld: [["unsupported_protocol", 2, 720]],
  },
};

function expectedSummary(name: string): SourceQuality {
  const e = EXPECTED[name];
  assert.ok(e, `${name}: this scenario has no expected summary`);
  return {
    observedMaxHeight: e.observed,
    deliverableMaxHeight: e.deliverable,
    withheld: e.withheld.map(([reason, count, maxObservedHeight]) => ({
      reason: reason as SourceQuality["withheld"][number]["reason"],
      count,
      maxObservedHeight,
    })),
    protectedUnenumerated: e.protectedUnenumerated ?? false,
    maybeProtectedObserved: e.maybeProtectedObserved ?? false,
  };
}

/**
 * HLS-7 carve-out: scenarios whose ADMITTED clear-HLS rows are now delivered,
 * and the exact preset ids clear HLS owns in each. Everything else those
 * scenarios produce is still compared with the golden record; every scenario
 * NOT listed here must still match it in full.
 */
const HLS_ACTIVATED: Record<string, readonly string[]> = {
  "case02-clear-hls-above-progressive": ["preset:best", "preset:2160", "preset:1080"],
};

/** A golden-shaped record with the HLS-owned ids removed. */
function withoutIds<T>(record: Record<string, T> | undefined, ids: ReadonlySet<string>): Record<string, T> {
  return Object.fromEntries(Object.entries(record ?? {}).filter(([id]) => !ids.has(id)));
}

describe("P1 rendition inventory: the corpus", () => {
  it("the corpus and the golden record describe the same scenarios", () => {
    const names = CORPUS.map((s) => s.name);
    assert.deepEqual(names, [...new Set(names)], "scenario names must be unique");
    assert.deepEqual(names.slice().sort(), Object.keys(GOLDEN).sort());
    assert.deepEqual(names.slice().sort(), Object.keys(EXPECTED).sort());
    assert.ok(names.length >= 25, "the corpus must keep its breadth");
    for (const name of Object.keys(HLS_ACTIVATED)) assert.ok(names.includes(name), name);
  });

  for (const scenario of CORPUS) {
    describe(scenario.name, () => {
      it("presets, selections, execution plans and selectors are IDENTICAL to pre-P1", async () => {
        const golden = GOLDEN[scenario.name]!;
        assert.equal(golden.ok, true, "every corpus scenario analyzed successfully before P1");

        const { video, selections, hlsSelections } = await analyzeScenario(scenario);
        const { sourceQuality, ...identity } = video;
        assert.ok(sourceQuality, "the new field exists...");

        // HLS-7: the ids clear HLS owns in this scenario, and nothing else.
        const hlsIds = new Set(HLS_ACTIVATED[scenario.name] ?? []);
        assert.deepEqual(Object.keys(hlsSelections).sort(), [...hlsIds].sort(), "exactly the carved-out ids");
        const progressivePresets = (presets: readonly { id: string }[]) =>
          presets.filter((p) => !hlsIds.has(p.id));
        const goldenVideo = golden.video as { presets: { id: string }[] };

        assert.deepEqual(
          { ...identity, presets: progressivePresets(identity.presets) },
          { ...goldenVideo, presets: progressivePresets(goldenVideo.presets) },
          "...and nothing else moved",
        );
        assert.deepEqual(JSON.parse(JSON.stringify(selections)), withoutIds(golden.selections, hlsIds));

        // The same presets must still derive the same plans and the same
        // yt-dlp selectors: identity of the metadata is not identity of
        // execution unless execution is re-derived and compared too.
        const plans: Record<string, unknown> = {};
        const selectors: Record<string, string[]> = {};
        for (const preset of video.presets) {
          const plan = deriveExecutionPlan({ strategy: "yt-dlp", video, selections, hlsSelections }, preset.id);
          if (hlsIds.has(preset.id)) {
            // HLS-owned: VideoFetch's own acquisition, so there is no yt-dlp
            // selector to compare — and none may exist.
            assert.equal(plan.strategy === "yt-dlp" ? plan.generic.operation : null, "clear-hls-remux");
            assert.equal(selections[preset.id], undefined);
            continue;
          }
          plans[preset.id] = plan;
          const value = selections[preset.id]!;
          const members = value.kind === "single" ? [value.source] : [value.pair.video, value.pair.audio];
          selectors[preset.id] = members.map(buildGenericFormatSelector);
        }
        assert.deepEqual(JSON.parse(JSON.stringify(plans)), withoutIds(golden.plans, hlsIds));
        assert.deepEqual(selectors, withoutIds(golden.selectors, hlsIds));
      });

      it("reports exactly the expected source quality", async () => {
        const { video } = await analyzeScenario(scenario);
        assert.deepEqual(sourceQualityOf(video), expectedSummary(scenario.name));
      });

      it("the summary is self-consistent, bounded, and free of upstream data", async () => {
        const { video, selections, hlsSelections } = await analyzeScenario(scenario);
        const quality = sourceQualityOf(video);

        // HLS-7: no private playlist location reaches the public body.
        const publicBody = JSON.stringify(WorkerAnalyzeSuccessSchema.parse({ success: true, video }));
        for (const forbidden of ["CORPUS_PRIVATE_HLS_TOKEN", "media.example.invalid", "m3u8", "playlistUrl"]) {
          assert.equal(publicBody.includes(forbidden), false, forbidden);
        }
        for (const selection of Object.values(hlsSelections)) {
          assert.equal(publicBody.includes(selection.playlistUrl), false);
        }

        // The contract's own refinements, applied to the emitted value.
        assert.deepEqual(SourceQualitySchema.parse(quality), quality);

        // Deliverable can never exceed observed...
        if (quality.deliverableMaxHeight !== null) {
          assert.ok(quality.observedMaxHeight !== null);
          assert.ok(quality.deliverableMaxHeight <= quality.observedMaxHeight);
        }
        // ...and every observed height above it is explained by a reason.
        const withheldMax = quality.withheld.reduce<number | null>(
          (max, e) => (e.maxObservedHeight === null ? max : Math.max(max ?? 0, e.maxObservedHeight)),
          null,
        );
        const explained = [quality.deliverableMaxHeight, withheldMax].filter(
          (h): h is number => h !== null,
        );
        assert.equal(quality.observedMaxHeight, explained.length === 0 ? null : Math.max(...explained));

        let total = 0;
        for (const entry of quality.withheld) {
          assert.ok(entry.count >= 1 && entry.count <= SOURCE_QUALITY_MAX_COUNT);
          total += entry.count;
          if (entry.maxObservedHeight !== null) {
            assert.ok(entry.maxObservedHeight >= 1 && entry.maxObservedHeight <= SOURCE_QUALITY_MAX_HEIGHT);
          }
        }
        assert.ok(total <= SOURCE_QUALITY_MAX_COUNT);

        // The public body carries no private analysis state and no upstream id.
        const body = JSON.stringify(WorkerAnalyzeSuccessSchema.parse({ success: true, video }));
        for (const forbidden of ["audioConstraint", "videoConstraint", "selections", "acodec", "vcodec", "b*["]) {
          assert.equal(body.includes(forbidden), false, forbidden);
        }
        for (const value of Object.values(selections)) {
          const members = value.kind === "single" ? [value.source] : [value.pair.video, value.pair.audio];
          for (const member of members) {
            assert.equal(
              JSON.stringify(quality).includes(member.formatId),
              false,
              "no upstream format id may appear in the public summary",
            );
          }
        }
      });
    });
  }
});

describe("P1 rendition inventory: segmented DASH and non-admitted HLS stay inventory-only", () => {
  // case02 left this list in HLS-7: its clear-HLS rows are admitted and now
  // delivered (see the HLS-7 describe below). What remains are manifests clear
  // HLS v1 does not take — segmented DASH, an HLS row with no playlist URL and a
  // hostile height, and X-shaped HLS video with no proven audio.
  const manifestScenarios = [
    "case03-segmented-dash-above-progressive",
    "case18-hostile-height-not-a-fact",
    "x-synthetic-x-progressive-unknown-audio-ffmpeg",
  ];

  for (const name of manifestScenarios) {
    it(`${name}: manifest renditions are counted but never executable`, async () => {
      const scenario = CORPUS.find((s) => s.name === name)!;
      const { video, selections, hlsSelections } = await analyzeScenario(scenario);
      assert.deepEqual(hlsSelections, {}, "no clear-HLS ownership either");

      // Which upstream ids belong to a manifest protocol, per the document.
      const formats = (documentOf(scenario).formats ?? []) as Array<Record<string, unknown>>;
      const manifestIds = new Set(
        formats
          .filter((f) => {
            const protocol = String(f.protocol ?? "").toLowerCase();
            return protocol.startsWith("m3u8") || protocol.startsWith("http_dash_segments");
          })
          .map((f) => String(f.format_id)),
      );
      assert.ok(manifestIds.size > 0, "this scenario must actually carry manifest formats");

      for (const [presetId, value] of Object.entries(selections)) {
        const members = value.kind === "single" ? [value.source] : [value.pair.video, value.pair.audio];
        for (const member of members) {
          assert.equal(manifestIds.has(member.formatId), false, `${presetId} must not name a manifest rendition`);
          // Belt and braces: the only protocols a selection may bind.
          assert.ok(["http", "https"].includes(member.protocol));
          assert.match(buildGenericFormatSelector(member), /\[protocol="https?"\]/);
        }
      }

      // Every preset is still derivable; none of them acquires a manifest.
      for (const preset of video.presets) {
        const plan = deriveExecutionPlan({ strategy: "yt-dlp", video, selections, hlsSelections }, preset.id);
        assert.notEqual(plan.strategy === "yt-dlp" ? plan.generic.operation : null, "clear-hls-remux");
      }

      // And the renditions did reach the inventory.
      const quality = sourceQualityOf(video);
      const protocolEntry = quality.withheld.find((e) => e.reason === "unsupported_protocol");
      assert.ok(protocolEntry, "manifest renditions must be accounted for, not dropped");
      assert.equal(protocolEntry.count, manifestIds.size - countAudioOnly(formats));
    });
  }

  function countAudioOnly(formats: Array<Record<string, unknown>>): number {
    return formats.filter(
      (f) =>
        String(f.vcodec ?? "").toLowerCase() === "none" &&
        (String(f.protocol ?? "").toLowerCase().startsWith("m3u8") ||
          String(f.protocol ?? "").toLowerCase().startsWith("http_dash_segments")),
    ).length;
  }

  it("an HLS-only document whose rows carry no playlist URL yields no presets, exactly as before", async () => {
    // Without a `url`, no row passes clear-HLS admission, so HLS-7 has nothing
    // to activate and the document reads exactly as it did before it.
    const document = {
      _type: "video",
      title: "HLS only",
      duration: 60,
      formats: [
        { format_id: "hls-720", ext: "mp4", protocol: "m3u8_native", height: 720, vcodec: "avc1.4d401f", acodec: "mp4a.40.2", video_ext: "mp4", audio_ext: "none" },
        { format_id: "hls-2160", ext: "mp4", protocol: "m3u8_native", height: 2160, vcodec: "avc1.640033", acodec: "mp4a.40.2", video_ext: "mp4", audio_ext: "none" },
      ],
    };
    const { video, selections } = await analyzeGenericMediaInternal(SAFE_URL, {
      limits: { analysisTimeoutSeconds: 45, maxVideoDurationSeconds: 7200, maxFileSizeBytes: 4 * 1024 ** 3 },
      ffmpegAvailable: true,
      runner: async () => ({ code: 0, stdout: JSON.stringify(document), stderr: "" }),
      probeRuntime: async () => ({ available: true, version: "2026.08.19", reason: "ok" as const }),
      validateUrl: async (raw: string) => ({ url: raw, hostname: new URL(raw).hostname }),
    });

    assert.deepEqual(video.presets, []);
    assert.deepEqual(selections, {});
    assert.deepEqual(video.formats, []);
    assert.deepEqual(sourceQualityOf(video), {
      observedMaxHeight: 2160,
      deliverableMaxHeight: null,
      withheld: [{ reason: "unsupported_protocol", count: 2, maxObservedHeight: 2160 }],
      protectedUnenumerated: false,
      maybeProtectedObserved: false,
    });
  });
});

describe("HLS-7 rendition inventory: admitted clear HLS is deliverable, and only it", () => {
  const case02 = () => CORPUS.find((s) => s.name === "case02-clear-hls-above-progressive")!;
  const HLS_URL = (tag: string) =>
    `https://media.example.invalid/hls/${tag}/media.m3u8?sig=CORPUS_PRIVATE_HLS_TOKEN`;
  const run = (document: Record<string, unknown>, ffmpegAvailable = true) =>
    analyzeGenericMediaInternal(SAFE_URL, {
      limits: { analysisTimeoutSeconds: 45, maxVideoDurationSeconds: 7200, maxFileSizeBytes: 4 * 1024 ** 3 },
      ffmpegAvailable,
      runner: async () => ({ code: 0, stdout: JSON.stringify(document), stderr: "" }),
      probeRuntime: async () => ({ available: true, version: "2026.08.19", reason: "ok" as const }),
      validateUrl: async (raw: string) => ({ url: raw, hostname: new URL(raw).hostname }),
    });
  const hlsRow = (id: string, height: number, over: Record<string, unknown> = {}) => ({
    format_id: id, ext: "mp4", protocol: "m3u8_native", height, vcodec: "avc1.640028",
    acodec: "mp4a.40.2", video_ext: "mp4", audio_ext: "none", url: HLS_URL(id), ...over,
  });
  const progressiveRow = (id: string, height: number) => ({
    format_id: id, ext: "mp4", protocol: "https", height, vcodec: "avc1.640028",
    acodec: "mp4a.40.2", video_ext: "mp4", audio_ext: "none", filesize: 1024,
  });
  const doc = (formats: Array<Record<string, unknown>>) => ({
    _type: "video", title: "HLS-7 inventory", duration: 60, formats,
  });

  it("case02: the taller HLS rungs are delivered, the progressive 720 is untouched", async () => {
    const { video, selections, hlsSelections } = await analyzeScenario(case02());
    const hls = (id: string, label: string, resolution: string) => ({
      id, label, resolution, container: "mp4", fileSize: null, hasVideo: true, hasAudio: true,
      formatId: id, videoCodec: null, audioCodec: null, fps: null,
    });
    const golden = GOLDEN["case02-clear-hls-above-progressive"]!.video as { presets: Array<{ id: string }> };
    const goldenPreset = (id: string) => golden.presets.find((p) => p.id === id);

    assert.deepEqual(video.presets, [
      hls("preset:best", "Best available", "2160p"),
      hls("preset:2160", "2160p / 4K", "2160p"),
      hls("preset:1080", "1080p", "1080p"),
      goldenPreset("preset:720"),
      goldenPreset("preset:audio"),
      goldenPreset("preset:mp3"),
    ]);
    // Private ownership: disjoint, and the SAME 2160 rendition behind best.
    assert.deepEqual(Object.keys(selections).sort(), ["preset:720", "preset:audio", "preset:mp3"]);
    assert.deepEqual(hlsSelections, {
      "preset:best": { playlistUrl: HLS_URL("2160"), height: 2160 },
      "preset:2160": { playlistUrl: HLS_URL("2160"), height: 2160 },
      "preset:1080": { playlistUrl: HLS_URL("1080"), height: 1080 },
    });
    // The audio-only HLS row carries a URL too, and is still no product.
    assert.equal(JSON.stringify(hlsSelections).includes("audio-en"), false);
    // `merge` still means the split merge; an HLS remux never sets it.
    assert.deepEqual(video.capabilities, { mp3: true, merge: false });
    assert.deepEqual(sourceQualityOf(video), expectedSummary("case02-clear-hls-above-progressive"));
  });

  it("case02 WITHOUT Worker FFmpeg: exactly the pre-HLS-7 withheld result", async () => {
    const { video, selections, hlsSelections } = await run(documentOf(case02()), false);
    assert.deepEqual(hlsSelections, {});
    assert.deepEqual(video.presets.map((p) => p.id), ["preset:best", "preset:720"]);
    assert.equal(Object.values(selections).every((v) => v.kind === "single" && v.source.formatId === "p720"), true);
    assert.deepEqual(sourceQualityOf(video), {
      observedMaxHeight: 2160,
      deliverableMaxHeight: 720,
      withheld: [{ reason: "unsupported_protocol", count: 2, maxObservedHeight: 2160 }],
      protectedUnenumerated: false,
      maybeProtectedObserved: false,
    });
  });

  it("counts a rendition behind both preset:best and its rung ONCE", () => {
    const { inventory } = analyzeGenericFormats(documentOf(case02()).formats as never, {
      ffmpegAvailable: true,
      maxFileSizeBytes: 4 * 1024 ** 3,
    });
    assert.deepEqual(
      inventory.renditions.map((r) => [r.observed.height, r.observed.protocol, r.disposition]),
      [
        [720, "progressive", "deliverable"],
        [1080, "hls", "deliverable"],
        [2160, "hls", "deliverable"],
      ],
    );
  });

  it("an HLS rendition that loses its rung to progressive is not_selected", async () => {
    const { video, hlsSelections } = await run(doc([progressiveRow("p1080", 1080), hlsRow("h1080", 1080)]));
    assert.deepEqual(hlsSelections, {}, "progressive keeps the equal rung");
    assert.deepEqual(sourceQualityOf(video).withheld, [
      { reason: "not_selected", count: 1, maxObservedHeight: 1080 },
    ]);
    assert.equal(sourceQualityOf(video).deliverableMaxHeight, 1080);
  });

  it("an HLS rendition that loses its rung to an EARLIER HLS rendition is not_selected", async () => {
    const { video, hlsSelections } = await run(doc([hlsRow("first", 1080), hlsRow("second", 1080)]));
    assert.equal(hlsSelections["preset:1080"]?.playlistUrl, HLS_URL("first"));
    assert.deepEqual(sourceQualityOf(video).withheld, [
      { reason: "not_selected", count: 1, maxObservedHeight: 1080 },
    ]);
  });

  it("segmented DASH stays unsupported_protocol even carrying a URL, with FFmpeg", async () => {
    const dash = hlsRow("dash-2160", 2160, { protocol: "http_dash_segments", url: "https://media.example.invalid/dash/a.mpd" });
    const { video, selections, hlsSelections } = await run(doc([progressiveRow("p720", 720), dash]));
    assert.deepEqual(hlsSelections, {});
    assert.equal(JSON.stringify(selections).includes("dash-2160"), false);
    assert.deepEqual(sourceQualityOf(video).withheld, [
      { reason: "unsupported_protocol", count: 1, maxObservedHeight: 2160 },
    ]);
  });

  it("an `m3u8` (not `m3u8_native`) rendition stays unsupported_protocol", async () => {
    const { video, hlsSelections } = await run(doc([progressiveRow("p720", 720), hlsRow("m3u8-2160", 2160, { protocol: "m3u8" })]));
    assert.deepEqual(hlsSelections, {});
    assert.deepEqual(sourceQualityOf(video).withheld, [
      { reason: "unsupported_protocol", count: 1, maxObservedHeight: 2160 },
    ]);
  });
});

describe("P1 rendition inventory: protection signals", () => {
  const baseFormats: Array<Record<string, unknown>> = [
    { format_id: "p720", ext: "mp4", protocol: "https", height: 720, vcodec: "avc1.640028", acodec: "mp4a.40.2", video_ext: "mp4", audio_ext: "none", filesize: 1024 },
  ];
  const run = async (document: Record<string, unknown>) =>
    analyzeGenericMediaInternal(SAFE_URL, {
      limits: { analysisTimeoutSeconds: 45, maxVideoDurationSeconds: 7200, maxFileSizeBytes: 4 * 1024 ** 3 },
      ffmpegAvailable: true,
      runner: async () => ({ code: 0, stdout: JSON.stringify(document), stderr: "" }),
      probeRuntime: async () => ({ available: true, version: "2026.08.19", reason: "ok" as const }),
      validateUrl: async (raw: string) => ({ url: raw, hostname: new URL(raw).hostname }),
    });
  const doc = (extra: Record<string, unknown> = {}, formats = baseFormats) => ({
    _type: "video",
    title: "Protection",
    duration: 60,
    formats,
    ...extra,
  });

  it("a stripped-protected document reports existence, never an invented height", async () => {
    const { video } = await run(doc({ _has_drm: true }));
    const quality = sourceQualityOf(video);
    assert.equal(quality.protectedUnenumerated, true);
    // The clear ladder's own maximum, and nothing above it.
    assert.equal(quality.observedMaxHeight, 720);
    assert.equal(quality.deliverableMaxHeight, 720);
    assert.deepEqual(quality.withheld, []);
  });

  it("only an exact `true` means renditions were stripped", async () => {
    for (const signal of [false, null, "true", 1, "maybe", undefined, {}]) {
      const { video } = await run(doc(signal === undefined ? {} : { _has_drm: signal }));
      assert.equal(
        sourceQualityOf(video).protectedUnenumerated,
        false,
        `_has_drm=${JSON.stringify(signal)} must not claim stripped renditions`,
      );
    }
  });

  it("a `maybe` marker is recorded and changes nothing about delivery", async () => {
    const plain = await run(doc());
    const marked = await run(doc({}, [{ ...baseFormats[0]!, has_drm: "maybe" }]));

    assert.equal(sourceQualityOf(plain.video).maybeProtectedObserved, false);
    assert.equal(sourceQualityOf(marked.video).maybeProtectedObserved, true);

    // Delivery is byte-identical: same presets, same selections.
    assert.deepEqual(marked.video.presets, plain.video.presets);
    assert.deepEqual(marked.selections, plain.selections);
    assert.equal(sourceQualityOf(marked.video).deliverableMaxHeight, 720);
  });

  it("an unparseable protection value never fails the analysis", async () => {
    for (const signal of [{ nested: true }, ["array"], 42]) {
      const { video } = await run(doc({ _has_drm: signal }, [{ ...baseFormats[0]!, has_drm: signal }]));
      assert.equal(video.presets.length > 0, true, "a weird marker must not reduce capability");
      assert.equal(sourceQualityOf(video).maybeProtectedObserved, false);
    }
  });
});

describe("P1 rendition inventory: the public summary leaks nothing", () => {
  const SENTINEL = "SUPER_SECRET_VALUE";

  it("upstream strings never reach sourceQuality, the body, or an error", async () => {
    const document = {
      _type: "video",
      title: `A video ${SENTINEL}`,
      duration: 60,
      formats: [
        { format_id: "p720", ext: "mp4", protocol: "https", height: 720, vcodec: "avc1.640028", acodec: "mp4a.40.2", video_ext: "mp4", audio_ext: "none", filesize: 2048 },
        {
          format_id: `id-${SENTINEL}`,
          ext: `mov-${SENTINEL}`,
          protocol: "https",
          height: 1080,
          vcodec: `codec-${SENTINEL}`,
          acodec: `acodec-${SENTINEL}`,
          video_ext: `mov-${SENTINEL}`,
          format_note: `note-${SENTINEL}`,
          url: `https://cdn.example.invalid/${SENTINEL}.mp4`,
          manifest_url: `https://cdn.example.invalid/${SENTINEL}.m3u8`,
          http_headers: { Cookie: SENTINEL },
        },
        {
          format_id: `manifest-${SENTINEL}`,
          ext: "mp4",
          protocol: `proto-${SENTINEL}`,
          height: 900,
          vcodec: "avc1.640028",
          acodec: `acodec-${SENTINEL}`,
          video_ext: "mp4",
          audio_ext: "none",
          manifest_url: `https://cdn.example.invalid/${SENTINEL}.mpd`,
        },
      ],
    };

    const logged: string[] = [];
    const streams = [process.stdout, process.stderr] as const;
    const originals = streams.map((s) => s.write.bind(s));
    const console_ = { log: console.log, warn: console.warn, error: console.error, info: console.info, debug: console.debug };
    streams.forEach((s) => {
      s.write = ((chunk: unknown) => {
        logged.push(String(chunk));
        return true;
      }) as typeof s.write;
    });
    for (const key of Object.keys(console_) as Array<keyof typeof console_>) {
      console[key] = ((...args: unknown[]) => logged.push(args.map(String).join(" "))) as never;
    }

    try {
      const { video } = await analyzeGenericMediaInternal(SAFE_URL, {
        limits: { analysisTimeoutSeconds: 45, maxVideoDurationSeconds: 7200, maxFileSizeBytes: 4 * 1024 ** 3 },
        ffmpegAvailable: true,
        runner: async () => ({ code: 0, stdout: JSON.stringify(document), stderr: "" }),
        probeRuntime: async () => ({ available: true, version: "2026.08.19", reason: "ok" as const }),
        validateUrl: async (raw: string) => ({ url: raw, hostname: new URL(raw).hostname }),
      });

      const quality = sourceQualityOf(video);
      // The unsupported rendition WAS observed and classified...
      assert.equal(quality.observedMaxHeight, 1080);
      assert.equal(quality.deliverableMaxHeight, 720);
      assert.deepEqual(quality.withheld, [
        { reason: "unsupported_protocol", count: 1, maxObservedHeight: 900 },
        { reason: "unsupported_container", count: 1, maxObservedHeight: 1080 },
      ]);
      // ...without carrying any of its strings.
      assert.equal(JSON.stringify(quality).includes(SENTINEL), false);
      for (const entry of quality.withheld) {
        assert.ok((SOURCE_QUALITY_WITHHELD_REASONS as readonly string[]).includes(entry.reason));
      }
      assert.equal(
        JSON.stringify({ ...video, title: "" }).includes(SENTINEL),
        false,
        "only the sanitized title may ever carry upstream text",
      );
    } finally {
      streams.forEach((s, i) => {
        s.write = originals[i]!;
      });
      Object.assign(console, console_);
    }

    assert.equal(logged.join("").includes(SENTINEL), false, "nothing upstream may be logged");
  });

  it("a summary is made only of numbers, booleans and vocabulary values", async () => {
    const scenario = CORPUS.find((s) => s.name === "case11-not-selected-within-rung")!;
    const { video } = await analyzeScenario(scenario);
    const quality = sourceQualityOf(video);

    assert.deepEqual(Object.keys(quality).sort(), [
      "deliverableMaxHeight",
      "maybeProtectedObserved",
      "observedMaxHeight",
      "protectedUnenumerated",
      "withheld",
    ]);
    for (const entry of quality.withheld) {
      assert.deepEqual(Object.keys(entry).sort(), ["count", "maxObservedHeight", "reason"]);
      assert.equal(typeof entry.count, "number");
      assert.ok((SOURCE_QUALITY_WITHHELD_REASONS as readonly string[]).includes(entry.reason));
    }
  });
});

describe("P1 rendition inventory: bounds", () => {
  it("the public count bound covers the analyzer's own raw-format ceiling", () => {
    assert.ok(YTDLP_ANALYSIS_MAX_RAW_FORMATS <= SOURCE_QUALITY_MAX_COUNT);
  });

  it("a very wide ladder aggregates into ONE bounded entry", () => {
    const formats = Array.from({ length: YTDLP_ANALYSIS_MAX_RAW_FORMATS }, (_, i) => ({
      format_id: `hls-${i}`,
      ext: "mp4",
      protocol: "m3u8_native",
      height: 240 + (i % 8) * 120,
      vcodec: "avc1.640028",
      acodec: "mp4a.40.2",
      video_ext: "mp4",
      audio_ext: "none",
    }));
    const { build, inventory } = analyzeGenericFormats(formats, {
      ffmpegAvailable: true,
      maxFileSizeBytes: 4 * 1024 ** 3,
    });
    const quality = summarizeSourceQuality(inventory);

    assert.deepEqual(build.presets, []);
    assert.equal(inventory.renditions.length, YTDLP_ANALYSIS_MAX_RAW_FORMATS);
    assert.equal(quality.withheld.length, 1);
    assert.deepEqual(quality.withheld[0], {
      reason: "unsupported_protocol",
      count: YTDLP_ANALYSIS_MAX_RAW_FORMATS,
      maxObservedHeight: 1080,
    });
    assert.ok(JSON.stringify(quality).length < 400, "the public summary stays tiny");
    assert.deepEqual(SourceQualitySchema.parse(quality), quality);
  });

  it("a height above the public bound is not a fact", () => {
    const tall = (height: number) => ({
      format_id: "p",
      ext: "mp4",
      protocol: "https",
      height,
      vcodec: "avc1.640028",
      acodec: "mp4a.40.2",
      video_ext: "mp4",
      audio_ext: "none",
    });
    const at = summarizeSourceQuality(
      analyzeGenericFormats([tall(SOURCE_QUALITY_MAX_HEIGHT)], { ffmpegAvailable: true, maxFileSizeBytes: 4 * 1024 ** 3 }).inventory,
    );
    assert.equal(at.observedMaxHeight, SOURCE_QUALITY_MAX_HEIGHT);

    const over = summarizeSourceQuality(
      analyzeGenericFormats([tall(SOURCE_QUALITY_MAX_HEIGHT + 1)], { ffmpegAvailable: true, maxFileSizeBytes: 4 * 1024 ** 3 }).inventory,
    );
    assert.equal(over.observedMaxHeight, null, "an implausible height is dropped, never clamped");
    assert.equal(over.deliverableMaxHeight, null);
  });
});

describe("P1 rendition inventory: what counts as an observed video rendition", () => {
  const analyze = (formats: Array<Record<string, unknown>>) =>
    analyzeGenericFormats(formats, { ffmpegAvailable: true, maxFileSizeBytes: 4 * 1024 ** 3 });

  it("audio-only, storyboard, image and subtitle rows never inflate the observed height", () => {
    const junk = [
      { format_id: "sb", ext: "mhtml", protocol: "mhtml", height: 2160, vcodec: "none", acodec: "none", video_ext: "none", audio_ext: "none", format_note: "storyboard" },
      { format_id: "img", ext: "jpg", protocol: "https", height: 4320, vcodec: null, acodec: null, video_ext: "jpg", audio_ext: "none" },
      { format_id: "sub", ext: "vtt", protocol: "https", height: 4320, vcodec: null, acodec: null, video_ext: "vtt", audio_ext: "none" },
      { format_id: "aud", ext: "m4a", protocol: "https", height: 9999, vcodec: "none", acodec: "mp4a.40.2", video_ext: "none", audio_ext: "m4a" },
      { format_id: "prev", ext: "mp4", protocol: "https", height: 4320, vcodec: "avc1.4d401f", acodec: "none", video_ext: "mp4", audio_ext: "none", format_note: "preview image" },
    ];
    const { inventory } = analyze(junk);
    assert.deepEqual(inventory.renditions, []);
    assert.equal(summarizeSourceQuality(inventory).observedMaxHeight, null);
  });

  it("a named video codec is video evidence; an unknown codec needs a coherent container", () => {
    const { inventory } = analyze([
      { format_id: "codec", ext: "mkv", protocol: "https", height: 1080, vcodec: "avc1.640028", acodec: "mp4a.40.2", video_ext: "mkv", audio_ext: "none" },
      { format_id: "shape", ext: "mov", protocol: "https", height: 720, vcodec: null, acodec: null, video_ext: "mov", audio_ext: "none" },
      { format_id: "incoherent", ext: "mp4", protocol: "https", height: 2160, vcodec: null, acodec: null, video_ext: "webm", audio_ext: "none" },
    ]);
    assert.deepEqual(
      inventory.renditions.map((r) => [r.observed.height, r.observed.videoEvidence, r.observed.container]),
      [
        [1080, "codec", "mkv"],
        [720, "shape", "mov"],
      ],
    );
  });

  it("observed facts are closed values: protocol family, container, size state", () => {
    const { inventory } = analyze([
      { format_id: "a", ext: "mp4", protocol: "https", height: 720, vcodec: "avc1.640028", acodec: "mp4a.40.2", video_ext: "mp4", audio_ext: "none", filesize: 10 },
      { format_id: "b", ext: "mp4", protocol: "m3u8_native", height: 1080, vcodec: "avc1.640028", acodec: "none", video_ext: "mp4", audio_ext: "none", filesize_approx: 10 },
      { format_id: "c", ext: "mp4", protocol: "http_dash_segments", height: 1440, vcodec: "avc1.640028", acodec: "none", video_ext: "mp4", audio_ext: "none" },
      { format_id: "d", ext: "mp4", protocol: "rtmp", height: 240, vcodec: "avc1.640028", acodec: "none", video_ext: "mp4", audio_ext: "none" },
      { format_id: "e", ext: "mp4", height: 360, vcodec: "avc1.640028", acodec: "none", video_ext: "mp4", audio_ext: "none" },
    ]);
    assert.deepEqual(
      inventory.renditions.map((r) => [r.observed.protocol, r.observed.size]),
      [
        ["progressive", "exact"],
        ["hls", "estimated"],
        ["dash-segmented", "unknown"],
        ["other", "unknown"],
        ["unknown", "unknown"],
      ],
    );
  });

  it("every advertised video preset is backed by a rendition marked deliverable", async () => {
    for (const scenario of CORPUS) {
      const { video, selections, hlsSelections } = await analyzeScenario(scenario);
      const { inventory } = analyzeGenericFormats(
        (documentOf(scenario).formats ?? []) as never,
        {
          ffmpegAvailable: scenario.ffmpegAvailable,
          maxFileSizeBytes: scenario.maxFileSizeBytes,
        },
      );
      const deliverable = inventory.renditions.filter((r) => r.disposition === "deliverable");
      const videoPresets = video.presets.filter((p) => p.hasVideo);
      // HLS-7: an HLS-owned preset names its rendition by playlist location.
      // The corpus gives every admitted HLS row a distinct URL, so distinct
      // locations are distinct renditions here.
      const videoSources = new Set(
        videoPresets.map((p) => {
          const hls = hlsSelections[p.id];
          if (hls) return `hls:${hls.playlistUrl}`;
          const value = selections[p.id]!;
          return value.kind === "single" ? value.source.formatId : value.pair.video.formatId;
        }),
      );
      assert.equal(
        deliverable.length,
        videoSources.size,
        `${scenario.name}: one deliverable rendition per distinct advertised video source`,
      );
    }
  });
});

describe("P1 rendition inventory: direct analysis omits the field", () => {
  afterEach(() => {
    setSafeHttpTestHooks(null);
    setProcessRunnerTestHooks(null);
  });

  it("a direct-media result carries no sourceQuality at all", async () => {
    const head: SafeRequestOnce = async () => ({
      status: 200,
      headers: { "content-length": "2048", "content-type": "video/mp4" },
      body: null,
    });
    setSafeHttpTestHooks({ lookup: async () => [{ address: "93.184.216.34", family: 4 }], requestOnce: head });
    setProcessRunnerTestHooks({
      spawn: () => {
        throw new Error("no subprocess expected");
      },
    });

    const meta = await analyzeDirectMedia("https://cdn.example.com/clip.mp4");

    assert.equal(meta.extractor, "direct");
    assert.equal("sourceQuality" in meta, false, "direct analysis knows no source inventory");
    assert.ok(meta.presets.length > 0, "and still advertises exactly what it did before");
    // The contract accepts it precisely because the field is optional.
    assert.deepEqual(VideoMetadataSchema.parse(meta), meta);
  });
});
