// HLS-11 deterministic fixtures: real media, generated by the candidate
// image's own `/usr/bin/ffmpeg` from lavfi generators, packaged by FFmpeg's own
// HLS muxer, and served verbatim.
//
//   ts         1920x1080 H.264 + AAC, MPEG-TS segments       (HLS-V1-MUXED-TS)
//   fmp4       1920x1080 H.264 + AAC, init + fMP4 fragments  (HLS-V2-MUXED-FMP4)
//   fmp4-video 1920x1080 H.264 only, init + fMP4 fragments   (the lying-master negative)
//
// Every recipe pins x264 to one thread and asks for bit-exact muxing, so a
// second generation is byte-identical; the orchestrator measures that.
//
// Pure apart from the injected tool runner and the filesystem under `outDir`.

import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import {
  hls11MediaPlaylistUri,
  hls11RawFormatId,
  HLS11_RAW_FORMAT_NAME_PREFIX,
} from "../lib/hls11-fixture-url.mjs";

export const HLS11_FIXTURE_SPEC = Object.freeze({
  width: 1920,
  height: 1080,
  fps: 25,
  durationSeconds: 4,
  segmentSeconds: 1,
  gop: 25,
  sampleRate: 48000,
  videoCodecsAttribute: "avc1.640028",
  audioCodecsAttribute: "mp4a.40.2",
});

/** The renditions, by kind, and what each carries. */
export const HLS11_RENDITIONS = Object.freeze({
  ts: { segmentType: "mpegts", video: true, audio: true, extension: "ts" },
  fmp4: { segmentType: "fmp4", video: true, audio: true, extension: "m4s" },
  "fmp4-video": { segmentType: "fmp4", video: true, audio: false, extension: "m4s" },
});

const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");

/** The exact FFmpeg argv for one rendition, writing into `dir`. */
export function hls11FfmpegArgs(kind, dir) {
  const spec = HLS11_FIXTURE_SPEC;
  const rendition = HLS11_RENDITIONS[kind];
  if (!rendition) throw new Error(`unknown HLS-11 rendition ${String(kind)}`);
  const inputs = [
    "-f", "lavfi",
    "-i", `testsrc2=size=${spec.width}x${spec.height}:rate=${spec.fps}:duration=${spec.durationSeconds}`,
    ...(rendition.audio
      ? ["-f", "lavfi", "-i", `sine=frequency=440:sample_rate=${spec.sampleRate}:duration=${spec.durationSeconds}`]
      : []),
  ];
  const maps = rendition.audio ? ["-map", "0:v", "-map", "1:a"] : ["-map", "0:v"];
  const audio = rendition.audio
    ? ["-c:a", "aac", "-b:a", "64k", "-ac", "1", "-flags:a", "+bitexact"]
    : ["-an"];
  const segmentType = rendition.segmentType === "fmp4" ? "fmp4" : "mpegts";
  return [
    "-hide_banner", "-nostdin", "-loglevel", "error", "-y", "-fflags", "+bitexact",
    ...inputs,
    ...maps,
    "-c:v", "libx264", "-preset", "veryfast", "-threads", "1",
    "-pix_fmt", "yuv420p", "-profile:v", "high", "-level", "4.0",
    "-g", String(spec.gop), "-keyint_min", String(spec.gop), "-sc_threshold", "0",
    "-b:v", "600k", "-maxrate", "600k", "-bufsize", "600k", "-flags:v", "+bitexact",
    ...audio,
    "-map_metadata", "-1",
    "-t", String(spec.durationSeconds),
    "-f", "hls",
    "-hls_time", String(spec.segmentSeconds),
    "-hls_playlist_type", "vod",
    "-hls_segment_type", segmentType,
    ...(segmentType === "fmp4" ? ["-hls_fmp4_init_filename", "init.mp4"] : []),
    "-hls_segment_filename", join(dir, `seg-%d.${rendition.extension}`),
    join(dir, "media.m3u8"),
  ];
}

/**
 * Generates one rendition and reads it back: the playlist text exactly as
 * FFmpeg wrote it, the initialization segment (fMP4), and every segment with
 * its size and digest, in playlist order.
 */
export async function generateHls11Rendition({ ffmpegPath, runTool, kind, dir }) {
  const result = await runTool(ffmpegPath, hls11FfmpegArgs(kind, dir), { timeoutMs: 120_000 });
  if (result.code !== 0) throw new Error(`HLS-11 fixture generation failed for ${kind} (exit ${result.code})`);
  const playlistText = await readFile(join(dir, "media.m3u8"), "utf8");
  const rendition = HLS11_RENDITIONS[kind];
  const names = (await readdir(dir))
    .filter((name) => new RegExp(`^seg-\\d+\\.${rendition.extension}$`).test(name))
    .sort((a, b) => Number(a.slice(4).split(".")[0]) - Number(b.slice(4).split(".")[0]));
  const segments = [];
  for (const [index, name] of names.entries()) {
    const bytes = await readFile(join(dir, name));
    segments.push({ name, ordinal: index + 1, bytes, byteLength: bytes.byteLength, sha256: sha256(bytes) });
  }
  const init = rendition.segmentType === "fmp4" ? await readFile(join(dir, "init.mp4")) : null;
  const aggregate = Buffer.concat([...(init ? [init] : []), ...segments.map((s) => s.bytes)]);
  return {
    kind,
    segmentType: rendition.segmentType,
    playlistText,
    init: init ? { bytes: init, byteLength: init.byteLength, sha256: sha256(init) } : null,
    segments,
    aggregateBytes: aggregate.byteLength,
    aggregateSha256: sha256(aggregate),
    aggregatePath: null,
  };
}

/** The top-level ISO-BMFF box types of `bytes`, strictly. */
export function topLevelBoxTypes(bytes) {
  const types = [];
  let offset = 0;
  while (offset < bytes.byteLength) {
    if (offset + 8 > bytes.byteLength) throw new Error("truncated box header");
    const size = bytes.readUInt32BE(offset);
    const type = bytes.subarray(offset + 4, offset + 8).toString("latin1");
    if (size < 8 || offset + size > bytes.byteLength) throw new Error("malformed box length");
    types.push(type);
    offset += size;
  }
  return types;
}

// ── Playlists the fixture serves ───────────────────────────────────────────

/** The HTML page each case submits: an HTML5 `<video>` naming its master. */
export function hls11Page(caseName) {
  return (
    "<!doctype html>\n<html><head><meta charset=\"utf-8\">" +
    `<title>HLS-11 ${caseName}</title></head>\n<body>` +
    '<video controls><source src="master.m3u8" type="application/x-mpegURL"></video>' +
    "</body></html>\n"
  );
}

/**
 * A single-variant master naming the case's media playlist. `claimsAudio`
 * states the CODECS attribute the pinned yt-dlp will read: video + audio for
 * every muxed case — including the lying-master negative, whose rendition has
 * no audio at all.
 */
export function hls11Master(caseName, { claimsAudio = true } = {}) {
  const spec = HLS11_FIXTURE_SPEC;
  const codecs = claimsAudio ? `${spec.videoCodecsAttribute},${spec.audioCodecsAttribute}` : spec.videoCodecsAttribute;
  const name = hls11RawFormatId(caseName).slice("hls-".length);
  if (!name.startsWith(HLS11_RAW_FORMAT_NAME_PREFIX)) throw new Error("unexpected raw format name");
  return [
    "#EXTM3U",
    "#EXT-X-VERSION:7",
    `#EXT-X-STREAM-INF:BANDWIDTH=900000,RESOLUTION=${spec.width}x${spec.height},FRAME-RATE=${spec.fps}.000,CODECS="${codecs}",NAME="${name}"`,
    hls11MediaPlaylistUri(caseName),
    "",
  ].join("\n");
}

/**
 * The split master (§8/§9 evidence): a 1080p video-only variant that references
 * an audio group with a DEFAULT and a non-default rendition, plus a 720p
 * CONTROL variant that references no audio group and whose CODECS names only
 * video. The pinned yt-dlp prints both video variants with `acodec: "none"`
 * and no group relationship, which is what makes pairing unprovable.
 */
export function hls11SplitMaster() {
  return [
    "#EXTM3U",
    "#EXT-X-VERSION:7",
    '#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aud",NAME="Main",LANGUAGE="en",DEFAULT=YES,AUTOSELECT=YES,URI="audio-main.m3u8"',
    '#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aud",NAME="Alt",LANGUAGE="en",DEFAULT=NO,AUTOSELECT=NO,URI="audio-alt.m3u8"',
    '#EXT-X-STREAM-INF:BANDWIDTH=900000,RESOLUTION=1920x1080,CODECS="avc1.640028,mp4a.40.2",AUDIO="aud"',
    "video-1080.m3u8",
    '#EXT-X-STREAM-INF:BANDWIDTH=500000,RESOLUTION=1280x720,CODECS="avc1.64001f"',
    "video-720.m3u8",
    "",
  ].join("\n");
}

/** The fMP4 playlist with its map carrying a BYTERANGE (refused by the v2 grammar). */
export function hls11ByteRangePlaylist(fmp4PlaylistText, initByteLength) {
  const map = '#EXT-X-MAP:URI="init.mp4"';
  if (!fmp4PlaylistText.includes(map)) throw new Error("the fMP4 playlist carries no map line");
  return fmp4PlaylistText.replace(map, `${map},BYTERANGE="${initByteLength}@0"`);
}

/** The fMP4 playlist with an EXT-X-KEY line (refused by the grammar, never fetched). */
export function hls11EncryptedPlaylist(fmp4PlaylistText) {
  const lines = fmp4PlaylistText.split("\n");
  const at = lines.findIndex((line) => line.startsWith("#EXT-X-VERSION:"));
  if (at < 0) throw new Error("the fMP4 playlist carries no version line");
  lines.splice(at + 1, 0, '#EXT-X-KEY:METHOD=AES-128,URI="key.bin"');
  return lines.join("\n");
}
