// HLS-12 deterministic fixtures (HLS-SEPARATE-AUDIO-PAIRING-IMPLEMENTATION-001):
// real media, generated by the candidate image's own `/usr/bin/ffmpeg` from
// lavfi generators, packaged by FFmpeg's own HLS muxer, served verbatim; and
// hand-authored Master Playlists that state the one relationship under test.
//
// ── The recipes ────────────────────────────────────────────────────────────
//
//   pair-audio-late   ONE packager run, two renditions (`-var_stream_map`): a
//                     video-only fMP4 rendition and an audio-only fMP4 rendition
//                     whose audio input is offset +0.5 s, so the audio is first
//                     presented ~0.48 s after the video
//   pair-video-late   the same, with the audio input offset -0.5 s (and 0.5 s
//                     longer), so the VIDEO is first presented ~0.52 s after the
//                     audio and the audio must be the merge reference
//   aligned-video     a separate packager run: video only, no B-frames
//   aligned-audio     a separate packager run: audio only
//                     (together: a pair whose halves both start at exactly 0)
//   muxed-fmp4        one rendition carrying video AND audio (a negative)
//   audio-ts          an audio-only MPEG-TS rendition (a negative)
//
// The offsets are not asserted here: the orchestrator MEASURES every pair's
// source timing with the shared packet oracle before any job runs, and the
// offset cases must be discriminating. Every recipe pins x264 to one thread and
// asks for bit-exact muxing, so a second generation is byte-identical; the
// orchestrator measures that too.
//
// ── The masters ────────────────────────────────────────────────────────────
//
// Hand-authored, inside the candidate's closed master grammar, and carrying
// the private sentinels in every descriptive slot — GROUP-ID, NAME, LANGUAGE —
// and in every signed query, so a leak of any of them is detectable.
//
// Pure apart from the injected tool runner and the filesystem under `dir`.

import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import {
  hls12AltAudioPlaylistUri,
  hls12AudioPlaylistUri,
  hls12GroupId,
  hls12Language,
  hls12MasterUri,
  hls12RenditionName,
  hls12VideoPlaylistUri,
} from "../lib/hls12-fixture-url.mjs";

export { topLevelBoxTypes } from "./hls11-media.mjs";

export const HLS12_FIXTURE_SPEC = Object.freeze({
  width: 1920,
  height: 1080,
  fps: 25,
  durationSeconds: 4,
  segmentSeconds: 1,
  gop: 25,
  sampleRate: 48000,
  videoCodecsAttribute: "avc1.640028",
  audioCodecsAttribute: "mp4a.40.2",
});

/**
 * The closed recipe vocabulary. `layout: "pair"` writes two renditions from
 * one packager run (`v0` video, `v1` audio); `layout: "single"` writes one.
 */
export const HLS12_RECIPES = Object.freeze({
  "pair-audio-late": Object.freeze({ layout: "pair", audioOffset: "0.5", audioDurationSeconds: 4 }),
  "pair-video-late": Object.freeze({ layout: "pair", audioOffset: "-0.5", audioDurationSeconds: 4.5 }),
  "aligned-video": Object.freeze({ layout: "single", video: true, audio: false, segmentType: "fmp4" }),
  "aligned-audio": Object.freeze({ layout: "single", video: false, audio: true, segmentType: "fmp4" }),
  "muxed-fmp4": Object.freeze({ layout: "single", video: true, audio: true, segmentType: "fmp4" }),
  "audio-ts": Object.freeze({ layout: "single", video: false, audio: true, segmentType: "mpegts" }),
});

const HEAD = ["-hide_banner", "-nostdin", "-loglevel", "error", "-y", "-fflags", "+bitexact"];

const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");

function videoInput(spec) {
  return ["-f", "lavfi", "-i", `testsrc2=size=${spec.width}x${spec.height}:rate=${spec.fps}:duration=${spec.durationSeconds}`];
}

function audioInput(spec, { offset = null, durationSeconds = spec.durationSeconds } = {}) {
  return [
    ...(offset === null ? [] : ["-itsoffset", offset]),
    "-f", "lavfi",
    "-i", `sine=frequency=440:sample_rate=${spec.sampleRate}:duration=${durationSeconds}`,
  ];
}

function videoCodec(spec, { bframes = null } = {}) {
  return [
    "-c:v", "libx264", "-preset", "veryfast", "-threads", "1",
    "-pix_fmt", "yuv420p", "-profile:v", "high", "-level", "4.0",
    "-g", String(spec.gop), "-keyint_min", String(spec.gop), "-sc_threshold", "0",
    ...(bframes === null ? [] : ["-bf", String(bframes)]),
    "-b:v", "600k", "-maxrate", "600k", "-bufsize", "600k", "-flags:v", "+bitexact",
  ];
}

const AUDIO_CODEC = ["-c:a", "aac", "-b:a", "64k", "-ac", "1", "-flags:a", "+bitexact"];

function hlsMuxer(spec, segmentType) {
  return [
    "-map_metadata", "-1",
    "-f", "hls",
    "-hls_time", String(spec.segmentSeconds),
    "-hls_playlist_type", "vod",
    "-hls_segment_type", segmentType === "fmp4" ? "fmp4" : "mpegts",
    ...(segmentType === "fmp4"
      ? ["-hls_flags", "independent_segments", "-hls_fmp4_init_filename", "init.mp4"]
      : []),
  ];
}

/** The exact FFmpeg argv for one recipe, writing into `dir`. */
export function hls12FfmpegArgs(recipeName, dir) {
  const spec = HLS12_FIXTURE_SPEC;
  const recipe = HLS12_RECIPES[recipeName];
  if (!recipe) throw new Error(`unknown HLS-12 recipe ${String(recipeName)}`);
  if (recipe.layout === "pair") {
    return [
      ...HEAD,
      ...videoInput(spec),
      ...audioInput(spec, { offset: recipe.audioOffset, durationSeconds: recipe.audioDurationSeconds }),
      "-map", "0:v", "-map", "1:a",
      ...videoCodec(spec),
      ...AUDIO_CODEC,
      ...hlsMuxer(spec, "fmp4"),
      "-var_stream_map", "v:0,agroup:aud a:0,agroup:aud",
      "-hls_segment_filename", join(dir, "v%v/seg-%d.m4s"),
      "-master_pl_name", "packager-master.m3u8",
      join(dir, "v%v/media.m3u8"),
    ];
  }
  const extension = recipe.segmentType === "fmp4" ? "m4s" : "ts";
  const inputs = [...(recipe.video ? videoInput(spec) : []), ...(recipe.audio ? audioInput(spec) : [])];
  const maps = recipe.video && recipe.audio ? ["-map", "0:v", "-map", "1:a"] : ["-map", recipe.video ? "0:v" : "0:a"];
  return [
    ...HEAD,
    ...inputs,
    ...maps,
    ...(recipe.video ? videoCodec(spec, { bframes: 0 }) : ["-vn"]),
    ...(recipe.audio ? AUDIO_CODEC : ["-an"]),
    ...hlsMuxer(spec, recipe.segmentType),
    "-hls_segment_filename", join(dir, `seg-%d.${extension}`),
    join(dir, "media.m3u8"),
  ];
}

/** Reads one rendition directory back, in playlist order. */
async function readRendition(dir, segmentType) {
  const playlistText = await readFile(join(dir, "media.m3u8"), "utf8");
  const extension = segmentType === "fmp4" ? "m4s" : "ts";
  const entries = await readdir(dir);
  const names = entries
    .filter((name) => new RegExp(`^seg-\\d+\\.${extension}$`).test(name))
    .sort((a, b) => Number(a.slice(4).split(".")[0]) - Number(b.slice(4).split(".")[0]));
  const segments = [];
  for (const [index, name] of names.entries()) {
    const bytes = await readFile(join(dir, name));
    segments.push({ name, ordinal: index + 1, bytes, byteLength: bytes.byteLength, sha256: sha256(bytes) });
  }
  let init = null;
  if (segmentType === "fmp4") {
    const initNames = entries.filter((name) => /^init(?:_\d)?\.mp4$/.test(name));
    if (initNames.length !== 1) throw new Error("an fMP4 rendition must carry exactly one initialization segment");
    const bytes = await readFile(join(dir, initNames[0]));
    // The playlist must name exactly that file as its map.
    if (!playlistText.split("\n").includes(`#EXT-X-MAP:URI="${initNames[0]}"`)) {
      throw new Error("the fMP4 playlist does not name its initialization segment");
    }
    init = { name: initNames[0], bytes, byteLength: bytes.byteLength, sha256: sha256(bytes) };
  }
  const aggregate = Buffer.concat([...(init ? [init.bytes] : []), ...segments.map((s) => s.bytes)]);
  return {
    segmentType,
    playlistText,
    init,
    segments,
    aggregate,
    aggregateBytes: aggregate.byteLength,
    aggregateSha256: sha256(aggregate),
    aggregatePath: null,
  };
}

/**
 * Generates one recipe and reads it back. A pair recipe yields
 * `{ video, audio }`; a single recipe yields `{ main }`.
 */
export async function generateHls12Recipe({ ffmpegPath, runTool, recipeName, dir }) {
  const recipe = HLS12_RECIPES[recipeName];
  if (!recipe) throw new Error(`unknown HLS-12 recipe ${String(recipeName)}`);
  const result = await runTool(ffmpegPath, hls12FfmpegArgs(recipeName, dir), { timeoutMs: 120_000 });
  if (result.code !== 0) throw new Error(`HLS-12 fixture generation failed for ${recipeName} (exit ${result.code})`);
  if (recipe.layout === "pair") {
    return {
      video: await readRendition(join(dir, "v0"), "fmp4"),
      audio: await readRendition(join(dir, "v1"), "fmp4"),
    };
  }
  return { main: await readRendition(dir, recipe.segmentType) };
}

// ── What the fixture serves ────────────────────────────────────────────────

/** The HTML page each case submits: an HTML5 `<video>` naming its signed master. */
export function hls12Page(caseName) {
  return (
    "<!doctype html>\n<html><head><meta charset=\"utf-8\">" +
    `<title>HLS-12 ${caseName}</title></head>\n<body>` +
    `<video controls><source src="${hls12MasterUri(caseName)}" type="application/x-mpegURL"></video>` +
    "</body></html>\n"
  );
}

/**
 * The closed master shapes.
 *
 *   paired          ONE audio rendition, with a URI, in the group the one
 *                   video-only variant names: the relationship under test
 *   ambiguous       the variant's group holds TWO URI renditions
 *   no-audio-group  the variant names no group; an UNREFERENCED group with one
 *                   URI rendition sits beside it (the convenient audio row)
 *   resigned        `paired`, but the variant line carries a different
 *                   signature than the one the pinned yt-dlp saw
 *
 * `referenceBase` (a root-relative directory) prefixes every reference: the
 * redirect negative's TARGET master uses it, so a Product that followed the
 * redirect would find a provable pair there and the negative tests the
 * redirect refusal alone.
 */
export const HLS12_MASTER_SHAPES = Object.freeze(["paired", "ambiguous", "no-audio-group", "resigned"]);

export function hls12Master(caseName, shape, { referenceBase = "" } = {}) {
  if (!HLS12_MASTER_SHAPES.includes(shape)) throw new Error(`unknown HLS-12 master shape ${String(shape)}`);
  if (referenceBase !== "" && !(referenceBase.startsWith("/") && referenceBase.endsWith("/"))) {
    throw new Error("a reference base must be a root-relative directory");
  }
  const spec = HLS12_FIXTURE_SPEC;
  const group = hls12GroupId(caseName);
  const name = hls12RenditionName(caseName);
  const language = hls12Language(caseName);
  const rendition = (renditionName, uri, isDefault) =>
    `#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="${group}",NAME="${renditionName}",LANGUAGE="${language}",` +
    `DEFAULT=${isDefault ? "YES" : "NO"},AUTOSELECT=${isDefault ? "YES" : "NO"},CHANNELS="1",URI="${uri}"`;
  const grouped = shape !== "no-audio-group";
  const codecs = grouped ? `${spec.videoCodecsAttribute},${spec.audioCodecsAttribute}` : spec.videoCodecsAttribute;
  const variant =
    `#EXT-X-STREAM-INF:BANDWIDTH=900000,AVERAGE-BANDWIDTH=700000,RESOLUTION=${spec.width}x${spec.height},` +
    `FRAME-RATE=${spec.fps}.000,CODECS="${codecs}"${grouped ? `,AUDIO="${group}"` : ""}`;
  return [
    "#EXTM3U",
    "#EXT-X-VERSION:7",
    "#EXT-X-INDEPENDENT-SEGMENTS",
    rendition(name, referenceBase + hls12AudioPlaylistUri(caseName), true),
    ...(shape === "ambiguous"
      ? [rendition(`${name}_ALT`, referenceBase + hls12AltAudioPlaylistUri(caseName), false)]
      : []),
    variant,
    referenceBase + hls12VideoPlaylistUri(caseName, shape === "resigned" ? "RESIGNED" : "VIDEO"),
    "",
  ].join("\n");
}
