/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as SupportedSitesRouteImport } from './routes/supported-sites'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiDiagnosticsRouteImport } from './routes/api/diagnostics'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSitesRouteImport } from './routes/api/sites'
import { Route as ApiDownloadJobIdFileRouteImport } from './routes/api/download.$jobId.file'
import { Route as ApiDownloadJobIdStatusRouteImport } from './routes/api/download.$jobId.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportedSitesRoute = SupportedSitesRouteImport.update({
  id: '/supported-sites',
  path: '/supported-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnosticsRoute = ApiDiagnosticsRouteImport.update({
  id: '/api/diagnostics',
  path: '/api/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitesRoute = ApiSitesRouteImport.update({
  id: '/api/sites',
  path: '/api/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadJobIdFileRoute = ApiDownloadJobIdFileRouteImport.update({
  id: '/$jobId/file',
  path: '/$jobId/file',
  getParentRoute: () => ApiDownloadRoute,
} as any)
const ApiDownloadJobIdStatusRoute = ApiDownloadJobIdStatusRouteImport.update({
  id: '/$jobId/status',
  path: '/$jobId/status',
  getParentRoute: () => ApiDownloadRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/faq': typeof FaqRoute
  '/supported-sites': typeof SupportedSitesRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/diagnostics': typeof ApiDiagnosticsRoute
  '/api/download': typeof ApiDownloadRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/sites': typeof ApiSitesRoute
  '/api/download/$jobId/file': typeof ApiDownloadJobIdFileRoute
  '/api/download/$jobId/status': typeof ApiDownloadJobIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/faq': typeof FaqRoute
  '/supported-sites': typeof SupportedSitesRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/diagnostics': typeof ApiDiagnosticsRoute
  '/api/download': typeof ApiDownloadRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/sites': typeof ApiSitesRoute
  '/api/download/$jobId/file': typeof ApiDownloadJobIdFileRoute
  '/api/download/$jobId/status': typeof ApiDownloadJobIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/faq': typeof FaqRoute
  '/supported-sites': typeof SupportedSitesRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/diagnostics': typeof ApiDiagnosticsRoute
  '/api/download': typeof ApiDownloadRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/sites': typeof ApiSitesRoute
  '/api/download/$jobId/file': typeof ApiDownloadJobIdFileRoute
  '/api/download/$jobId/status': typeof ApiDownloadJobIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/faq'
    | '/supported-sites'
    | '/api/analyze'
    | '/api/diagnostics'
    | '/api/download'
    | '/api/health'
    | '/api/sites'
    | '/api/download/$jobId/file'
    | '/api/download/$jobId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/faq'
    | '/supported-sites'
    | '/api/analyze'
    | '/api/diagnostics'
    | '/api/download'
    | '/api/health'
    | '/api/sites'
    | '/api/download/$jobId/file'
    | '/api/download/$jobId/status'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/faq'
    | '/supported-sites'
    | '/api/analyze'
    | '/api/diagnostics'
    | '/api/download'
    | '/api/health'
    | '/api/sites'
    | '/api/download/$jobId/file'
    | '/api/download/$jobId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  FaqRoute: typeof FaqRoute
  SupportedSitesRoute: typeof SupportedSitesRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiDiagnosticsRoute: typeof ApiDiagnosticsRoute
  ApiDownloadRoute: typeof ApiDownloadRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSitesRoute: typeof ApiSitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supported-sites': {
      id: '/supported-sites'
      path: '/supported-sites'
      fullPath: '/supported-sites'
      preLoaderRoute: typeof SupportedSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnostics': {
      id: '/api/diagnostics'
      path: '/api/diagnostics'
      fullPath: '/api/diagnostics'
      preLoaderRoute: typeof ApiDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sites': {
      id: '/api/sites'
      path: '/api/sites'
      fullPath: '/api/sites'
      preLoaderRoute: typeof ApiSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$jobId/file': {
      id: '/api/download/$jobId/file'
      path: '/$jobId/file'
      fullPath: '/api/download/$jobId/file'
      preLoaderRoute: typeof ApiDownloadJobIdFileRouteImport
      parentRoute: typeof ApiDownloadRoute
    }
    '/api/download/$jobId/status': {
      id: '/api/download/$jobId/status'
      path: '/$jobId/status'
      fullPath: '/api/download/$jobId/status'
      preLoaderRoute: typeof ApiDownloadJobIdStatusRouteImport
      parentRoute: typeof ApiDownloadRoute
    }
  }
}

interface ApiDownloadRouteChildren {
  ApiDownloadJobIdFileRoute: typeof ApiDownloadJobIdFileRoute
  ApiDownloadJobIdStatusRoute: typeof ApiDownloadJobIdStatusRoute
}

const ApiDownloadRouteChildren: ApiDownloadRouteChildren = {
  ApiDownloadJobIdFileRoute: ApiDownloadJobIdFileRoute,
  ApiDownloadJobIdStatusRoute: ApiDownloadJobIdStatusRoute,
}

const ApiDownloadRouteWithChildren = ApiDownloadRoute._addFileChildren(
  ApiDownloadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  FaqRoute: FaqRoute,
  SupportedSitesRoute: SupportedSitesRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiDiagnosticsRoute: ApiDiagnosticsRoute,
  ApiDownloadRoute: ApiDownloadRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiSitesRoute: ApiSitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
